<a href="https://colab.research.google.com/github/Kazureee/supermarket-sales-dashboard/blob/main/supermarket_sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#import dataset from github
import pandas as pd

url = "https://raw.githubusercontent.com/Kazureee/supermarket-sales-dashboard/refs/heads/main/data/sales.csv"
df = pd.read_csv(url)

In [11]:
# Viewing initial rows of the dataset
df.head()

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax,total_price,reward_points
0,1,A,New York,Member,Male,Shampoo,Personal Care,5.50,3,1.16,17.66,1
1,2,B,Los Angeles,Normal,Female,Notebook,Stationery,2.75,10,1.93,29.43,0
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26,19.26,1
3,4,A,Chicago,Normal,Male,Detergent,Household,7.80,5,2.73,41.73,0
4,5,B,Los Angeles,Member,Female,Orange Juice,Beverages,3.50,7,1.72,26.22,2

In [12]:
#define the shape of the daata
df.shape

(1000, 12)

In [13]:
#columns
df.columns

Index(['sale_id', 'branch', 'city', 'customer_type', 'gender', 'product_name',
       'product_category', 'unit_price', 'quantity', 'tax', 'total_price',
       'reward_points'],
      dtype='object')

In [14]:
#dtypes
df.dtypes

sale_id               int64
branch               object
city                 object
customer_type        object
gender               object
product_name         object
product_category     object
unit_price          float64
quantity              int64
tax                 float64
total_price         float64
reward_points         int64
dtype: object

In [15]:
#describe the dataset
df.describe()

,sale_id,unit_price,quantity,tax,total_price,reward_points
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,10.836110,10.337000,7.758010,118.583900,6.057000
std,288.819436,5.775924,6.029908,6.538066,99.936441,9.350464
min,1.000000,1.020000,1.000000,0.080000,1.210000,0.000000
25%,250.750000,5.867500,5.000000,2.510000,38.380000,0.000000
50%,500.500000,10.615000,10.000000,5.870000,89.705000,0.000000
75%,750.250000,15.882500,16.000000,11.522500,176.072500,10.000000
max,1000.000000,20.980000,20.000000,28.390000,433.990000,43.000000

In [17]:
#checks in theres a missing data
df.isnull().sum()

sale_id             0
branch              0
city                0
customer_type       0
gender              0
product_name        0
product_category    0
unit_price          0
quantity            0
tax                 0
total_price         0
reward_points       0
dtype: int64

In [20]:
#creates calculated total column
df["calculated_total"] = df["unit_price"] * df["quantity"]
df[["unit_price", "quantity", "calculated_total"]].head(10)

   unit_price  quantity  calculated_total
0        5.50         3             16.50
1        2.75        10             27.50
2        1.20        15             18.00
3        7.80         5             39.00
4        3.50         7             24.50
5       11.24         9            101.16
6       10.71         1             10.71
7       18.23         9            164.07
8       14.15        20            283.00
9       18.42        19            349.98

In [27]:
# “Can you show me all sales from Branch A by female customers?”
df.query("branch == 'A' and gender == 'Female'").head(10)

,sale_id,branch,city,customer_type,gender,product_name,product_category,unit_price,quantity,tax,total_price,reward_points,calculated_total
2,3,A,New York,Member,Female,Apple,Fruits,1.20,15,1.26,19.26,1,18.00
8,9,A,Chicago,Member,Female,Apple,Fruits,14.15,20,19.81,302.81,30,283.00
12,13,A,New York,Normal,Female,Orange Juice,Household,3.29,4,0.92,14.08,0,13.16
22,23,A,New York,Member,Female,Shampoo,Beverages,1.95,16,2.18,33.38,3,31.20
27,28,A,New York,Member,Female,Detergent,Personal Care,16.46,17,19.59,299.41,29,279.82
31,32,A,New York,Member,Female,Orange Juice,Stationery,5.39,3,1.13,17.30,1,16.17
38,39,A,New York,Member,Female,Notebook,Beverages,15.34,15,16.11,246.21,24,230.10
39,40,A,New York,Normal,Female,Apple,Fruits,1.17,11,0.90,13.77,0,12.87
40,41,A,New York,Member,Female,Notebook,Household,10.80,10,7.56,115.56,11,108.00
42,43,A,New York,Normal,Female,Notebook,Fruits,4.17,2,0.58,8.92,0,8.34